Swap size and count in calloc due to GCC 14 throwing errors
There are 2 instances and here is the first one:
lib/osdep/network.c:77:41: error: 'calloc' sizes specified with 'sizeof' in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
   77 |         pktbuf = (char *) calloc(sizeof(char), pktlen);
      |                                         ^~~~