airodump-ng.c: Add missing import on inttypes.h
 Otherwise the build fails with:
 src/airodump-ng/airodump-ng.c: In function ‘main’:
 src/airodump-ng/airodump-ng.c:6592:55: error: expected ‘)’ before ‘SCNd16’
  6592 |                                 if (sscanf(optarg, "%" SCNd16, &lopt.min_power) != 1)
       |                                           ~           ^~~~~~~
       |                                                       )
 src/airodump-ng/airodump-ng.c:86:1: note: ‘SCNd16’ is defined in header ‘<inttypes.h>’; did you forget to ‘#include <inttypes.h>’?
    85 | #include "radiotap/radiotap_iter.h"
   +++ |+#include <inttypes.h>
    86 |